version: '3'

services:
  secmasterapiidentityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

